language: objective-c
osx_image: xcode9
script:
  - swift build -c release -Xswiftc -static-stdlib
  - cp .build/release/genosia .
  - zip genosia-$TRAVIS_OS_NAME.zip genosia
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file:
    - genosia-$TRAVIS_OS_NAME.zip
  skip_cleanup: true
  on:
    tags: true